### ISSUE TITLE
numpy version 1.20 required or modify script

### ISSUE THREAD

**Issue by RDorney** [cafelton/FLAIR-fusion#1]
Hello @cafelton,
I'm looking to do a preliminary benchmark study on long-read fusion callers and was testing if I had installed FLAIR-Fusion properly.
However, I received an error message relating to the version of numpy I have used:

```
Traceback (most recent call last):
  File "/opt/FLAIR-fusion/19-03-2021-fasta-to-fusions-pipe.py", line 113, in <module>
    temp = numpy.fromstring(line.rstrip(), dtype=numpy.int, sep=",")
  File "/home/ryleyd/anaconda3/envs/flair/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```

 I was able to rectify this error by changing the code to from ```temp = numpy.fromstring(line.rstrip(), dtype=numpy.int, sep=",")``` to ```temp = numpy.fromstring(line.rstrip(), dtype=int, sep=",")```

Kind regards,
Ryley :)

**Comment by qinqian** [comment]
I fixed this problem on my fork @RDorney , please take a look here https://github.com/qinqian/FLAIR-fusion
